[package]
name = "ghost2-wrapper"
version = "0.1.0"
authors = ["cbryant02 <3ef4c1bb@opayq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "^0.4"
fern = "^0.5"
chrono = "^0.4"
iced = "^0.1"